[package]
name = "get-saying"
version = "0.1.0"
authors = ["Doug Schwartz <snoopdougiedoug@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.3"
getrandom = { version = "0.2", features = ["js"] }
